Added conversation and messages migration & model files as requested by the ticket
alkemyTech/Custom-chat-112 pull request #4
Opened 2022-01-12 21:53 UTC by AleYanczuk

**Conversation model**

- User 1 (user1: type integer)
- User 2 (user2: type integer)
- State (state: type string)

**Message model**
- User ID (user_id: type integer)
- Detail (detail: type string)
- Modified (modified: type boolean)

2022-01-12 22:47 UTC, gervic08 commented on app/models/conversation.rb
> +  belongs_to :message
Ale, cómo va? a mi no me cierran mucho las relaciones de la base.. entiendo que los usuarios tienen muchos mensajes a través de una conversación, en ese caso, la conversación tiene muchos mensajes, no uno solo, no? y belongs_to: message hace referencia a q la conversación tiene un solo mensaje asociado.. además de eso, la conversación es entre dos usuarios, no sería has_many :users?

2022-01-13 04:20 UTC, FernandoCiballero commented on app/models/conversation.rb
> +  belongs_to :message
Tal como dice @gervic08 , en este caso sería:
```suggestion
 has_many :messages, dependent: destroy
```

2022-01-13 04:22 UTC, FernandoCiballero commented on app/models/message.rb
> +  belongs_to :user
The same situation here:
```suggestion
  belongs_to :user
  belongs_to :conversation
```

2022-01-13 04:27 UTC, FernandoCiballero commented on db/migrate/20220112214138_create_conversation.rb
> +      t.integer :user2, null: false
These should be foreign keys, not just integer fields.
```suggestion
     t.references :user1, null: false, foreign_key: { to_table: :users }
      t.references :user2, null: false, foreign_key: { to_table: :users }
```

2022-01-13 04:30 UTC, FernandoCiballero commented on db/migrate/20220112213712_create_messages.rb
> +      t.integer :user_id, null: false
This needs to be configured as a `foreign key`:
```suggestion
      t.integer :user, null: false, foreign_key: true
```

2022-01-13 04:35 UTC, FernandoCiballero commented on app/models/conversation.rb
> +  acts_as_paranoid
You should add the delete_at field to the messages table for soft deletion.
[Link to documentation](https://github.com/ActsAsParanoid/acts_as_paranoid#create-migration)

2022-01-13 04:38 UTC, FernandoCiballero requested changes
Great job!!! Please review the requested changes.

2022-01-16 18:52 UTC, FernandoCiballero reviewed
Good job!!! I made a small modification to comply with Rubocop.

2022-01-16 18:53 UTC, merged